server:
  port: 8083

spring:
  application:
    name: report-service
  config:
    import: "optional:configserver:http://localhost:8181"

  datasource:
    url: jdbc:postgresql://localhost:5433/report-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: update

    hibernate:
      ddl-auto: update
  boot:
    admin:
          client:
            url: "http://localhost:8192"

logging:
  file:
   name: C:/Users/log/application.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

pdfDir: C:/Users/log/
csvDir: C:/Users/log/
reportFileName: ParkingLot-Report
reportFileNameDateFormat: dd_MMMM_yyyy
localDateFormat: "dd MMMM yyyy HH:mm:ss"
logoImgPath: C:/Users/log/logo.jpg
logoImgScale: 50,50
currencySymbol: $
table_noOfColumns: 6
table.columnNames: Parking Lot Name,Location,Total Capacity,Current Usage, Revenue,Usage History



management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always